name: Security Scan and Reporting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step for running SAST scan
      - name: Run SAST scan
        run: |
          # Команда для запуску SAST сканера та збереження звіту у JSON форматі
          # Наприклад, використання CodeQL
          codeql analyze --format=sarif ./path/to/source-code
          mv codeql_results.sarif sast-report.json

      # Step for running DAST scan
      - name: Run DAST scan
        run: |
          # Команда для запуску DAST сканера та збереження звіту у JSON форматі
          # Наприклад, використання OWASP ZAP
          zap-baseline.py -t http://localhost:3000/#/ -r dast-report.json

      # Step for sending SAST report to DefectDojo
      - name: Send SAST report to DefectDojo
        run: |
          defectdojo-cli import sast-report --file sast-report.json --api-key 7addd800d84db0f94778bf1f42c45b041801cf9b --url http://localhost:8080

      # Step for sending DAST report to DefectDojo
      - name: Send DAST report to DefectDojo
        run: |
          defectdojo-cli import dast-report --file dast-report.json --api-key 7addd800d84db0f94778bf1f42c45b041801cf9b --url http://localhost:8080
